resource:
  groups:
  - host
  - os
  ignore:
  - "host.id"
  - "host.name"
  - "resource.name"
  report_additional: true
trace:
- match: http.server.*
  groups:
  - trace.http.server
  ignore:
  -
  report_additional: true
- match: http.client.*
  groups:
  - trace.http.client
  ignore:
  -
  report_additional: true
- match: xyz.regex
  groups:
  - 
  ignore:
  - 
  report_additional: true
metric:
log:
report_unmatched: true
server_address: localhost:4317
one_shot: true

