resource:
  groups:
  - host
  - os
  ignore:
  - "host.id"
  - "host.name"
  - "resource.name"
  report_additional: true
trace:
- match: xyz.regex
  groups:
  - 
  ignore:
  - 
  report_additional: true
metric:
log:
report_unmatched: true
server_address: localhost:4317

