name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  Run-SemConv-Checker:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
      - run: |
        go run ./cmd/

  Run-Server-Client:
    runs-on: ubuntu-latest
    needs: Run-SemConv-Checker
    steps:
        uses: actions/checkout@v4
      - run: |
        cd test
        go run ./http/
