name: GitHub Actions Demo
run-name: ${{ github.actor }} testing
on: [push, pull_request]
jobs:
  runchecker:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
          cache-dependency-path: "**/go.sum"

      - name: check out code
        uses: actions/checkout@v4
      - run: |
          go run ./cmd/

  runserverclient:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
          cache-dependency-path: "**/go.sum"

      - name: check out code
        uses: actions/checkout@v4
      - run: |
          sleep 10
          cd test
          go run ./http/
